### ISSUE TITLE
Any plans to publish on npm?

### ISSUE THREAD

**Issue by chmac** [Giwi/ryze-tello-sdk#3]
In looking for code to control the tello, I didn't see this on npm. I only later realised that searching GitHub might make sense. Then I find your repo, built in typescript, and it seems to be maintained, at least there have been commits over some period of time rather than a "bought tello, made package, moved on" timeline. :-)

Any plans to publish it as an npm package? Might help more folks find the code. I guess with the html and so on, maybe it's not exactly ready to be shipped as a standalone package.

Either way, thanks for sharing the code.

**Comment by Giwi** [comment]
Hi, I can :)

**Comment by Giwi** [comment]
yarn install @giwisoft/ryze-tello-sdk

Enjoy

**Comment by chmac** [comment]
@Giwi Haha, awesome, thanks a lot!
